--Domestic Report
Insert into IDM_MENU (CD,CREATED_BY,CREATED_DT,IS_DELETE,DSCP,ICON,IDX,IS_INACTIVE,NM,IS_SYSTEM,UPDATED_BY,UPDATED_DT,VERSION,MENU_TYPE_CD,SUB_TYPE,IS_FINANCIAL) 
    values ('MNU_GPCASH_BO_RPT_DOM_TRX',null,null,'N','Domestic Transfer Report',null,'999','N','Domestic Transfer Report','Y',null,null,'0','I',null,null);

Insert into IDM_MENU_TREE (ID,CREATED_BY,CREATED_DT,IDX,LVL,UPDATED_BY,UPDATED_DT,APP_CD,MENU_CD,PARENT_MENU_CD) 
    values ('MNU_GPCASH_BO_RPT_DOM_TRX72','SYSTEM',null,'7','2',null,null,'GPCASHBO','MNU_GPCASH_BO_RPT_DOM_TRX','MNU_GPCASH_BO_RPT_CUST');

-- 11 Record inserted - 10 Role + 1 Default role
INSERT INTO IDM_ROLE_MENU VALUE (SELECT SYS_GUID(), 'SYSTEM', SYSDATE, NULL, NULL, 'MNU_GPCASH_BO_RPT_DOM_TRX', RL.CD FROM
    IDM_ROLE RL WHERE IS_SYSTEM = 'Y' AND (CD LIKE 'BNK%MK%' OR CD = 'DEFAULT'));
    
INSERT INTO PRO_MENU_MAPPING (MENU_CD,MENU_SERVICE) values ('MNU_GPCASH_BO_RPT_DOM_TRX','DomesticReportSC');

select * From PRO_PENDING_DOWNLOAD where trunc(created_dt) = trunc(sysdate);
