package com.gpt.product.gpcash.corporate.transactionstatus;

public enum TransactionStatus {
	PENDING_APPROVE,
	APPROVAL_IN_PROGRESS,
	PENDING_RELEASE,
	PENDING_EXECUTE,
	EXECUTE_SUCCESS,
	EXECUTE_FAIL,
	EXECUTE_PARTIAL_SUCCESS,
	REJECTED,
	CANCELLED,
	EXPIRED,
	IN_PROGRESS_OFFLINE,
	FAIL_ON_RECURRING_CREATION
}
